replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/cocktailmanager/cocktail-manager-auth/cocktail-manager-auth
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: '3000'
  targetPort: '5000'

resources:
  limits:
    memory: '2Gi'
    cpu: '4'
  requests:
    memory: '512Mi'
    cpu: '0.5'

env:
  port: '5000'
  secretName: cocktail-manager-auth-secret
  DATABASE_URL: 'postgresql://postgres:k@T!gVWFdeaoF9Gbag62@cocktail-manager-db.default.svc.cluster.local:5432/cocktail-manager-db'