name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # SSH into the EC2 instance and create the destination directory
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST "mkdir -p /home/***/CocktailManager"

          # Copy the entire project to the EC2 instance
          scp -i private_key.pem -r -o StrictHostKeyChecking=no ./* $USER@$HOST:/home/ubuntu/CocktailManager

          # SSH into the EC2 instance
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST << 'ENDSSH'
            # Navigate to the api directory
            cd /path/to/CocktailManager/cocktail-manager-auth/api

            # Build and run the Docker containers
            docker-compose up -d --build
          ENDSSH
