name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Copy the entire project to the EC2 instance
          scp -i private_key.pem -r -o StrictHostKeyChecking=no ./* $USER@$HOST:/home/ubuntu/CocktailManager

            # SSH into the EC2 instance
            ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST << 'ENDSSH'
              # Add the current user to the docker group
              sudo usermod -aG docker $USER
              # Exit the SSH session
              exit
            ENDSSH

            # SSH into the EC2 instance again for the group changes to take effect
            ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST << 'ENDSSH'
            
            # Navigate to the api directory
            cd /home/ubuntu/CocktailManager/cocktail-manager-auth/api

          # Check if docker-compose is installed, and install it if not
          if ! command -v docker-compose &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y docker-compose
          fi

            # Build and run the Docker containers
            docker-compose up -d --build
          ENDSSH
